### PING TEXT/PLAIN (legacy)

GET /ping HTTP/1.1
Host: localhost:8080

### PING V1 (application/json) Content Type, Media Type MIME Type, via Query Param

GET /ping?version=1 HTTP/1.1
Host: localhost:8080
Accept: application/json

### PING V2 (application/json) via Header

GET /ping HTTP/1.1
Host: localhost:8080
Accept: application/json
X-TADS-Version: 2

### PING V3

GET /ping HTTP/1.1
Host: localhost:8080
Accept: application/vnd.tads-ms-util.v3+json

### Forca Senha V1

GET /api/v1/forca-senha/aaa
Host: localhost:8080
Accept: application/json

### Teste BusinessDay v1

POST /api/date/v1/business-days HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "startDate": "2025-05-07",
  "businessDays": 5
}

### PING V4 (Path Versioning)

GET /api/v4/ping HTTP/1.1
Host: localhost:8080
Accept: application/json

### TIME ELAPSED (legacy)

POST /api/time/elapsed HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "startTime": "10:00:00",
  "endTime": "15:30:45"
}

### TIME ELAPSED V2 (Path Versioning)

POST /api/time/v2/elapsed HTTP/1.1
Host: localhost:8081
Content-Type: application/json
Accept: application/json

{
  "startTime": "10:00:00",
  "endTime": "15:30:45"
}
 
