name: Build and Release

on:
  push:
    tags:
      - 'v*'
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Tornar Gradle Executavel
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build
       
      - name: Criar Release no GitHub
        uses: softprops/action-gh-release@v2
        with:
          tag_name: 'v0.0.1-SNAPSHOT'
          generate_release_notes: true
          files: build/libs/*.jar
        env:
          GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
